# Generated by Django 4.0.2 on 2023-04-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profile_options_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
