# Generated by Django 3.2.9 on 2023-04-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_friend_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
