# Generated by Django 4.0.2 on 2023-05-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_friend_idusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='IDUsuario',
            new_name='id_friend',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to='registration.Friend'),
        ),
    ]
