# Generated by Django 4.0.2 on 2023-05-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_rename_idusuario_friend_id_friend_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
    ]
