# Generated by Django 3.2.9 on 2023-05-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('sol_id_autoincremental', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sol', models.DateField()),
                ('unidad', models.TextField()),
                ('depto', models.TextField()),
                ('rubro', models.TextField()),
                ('objeto', models.TextField()),
                ('prioridad', models.TextField()),
                ('esp_tec', models.FileField(upload_to='media/tecnica')),
                ('justifica', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('u_medida', models.TextField()),
                ('cant', models.FloatField()),
                ('observa', models.TextField()),
                ('primer_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unhido.solicitud')),
            ],
        ),
    ]
