# Generated by Django 4.0.2 on 2023-05-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unhido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='valida',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
