# Generated by Django 4.0.2 on 2023-04-27 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_profile_last_name_profile_name'),
        ('mychatapp', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver', to='registration.profile'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to='registration.profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
