# Generated by Django 4.0.2 on 2023-05-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0007_alter_chatmessage_msg_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_receiver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
