# Generated by Django 4.0.2 on 2023-05-06 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_friend_idusuario'),
        ('mychatapp', '0008_alter_chatmessage_msg_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver', to='registration.profile'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to='registration.profile'),
        ),
    ]
